[CmdletBinding()]
param([string]$ProjectRoot='.',[switch]$RunBuild,[switch]$ExportJson)
$ErrorActionPreference='Stop'
$root=(Resolve-Path $ProjectRoot).Path
$checks=@()
function Check($area,$name,$ok){$script:checks += [pscustomobject]@{Area=$area;Check=$name;Passed=[bool]$ok};Write-Host ("[{0}] {1} :: {2}" -f ($(if($ok){'PASS'}else{'FAIL'}),$area,$name)) -ForegroundColor $(if($ok){'Green'}else{'Red'})}
function Text($rel){Get-Content (Join-Path $root $rel) -Raw}

$props=Text 'Directory.Build.props'
$vm=Text 'src\MystTiq.Desktop\ViewModels\MainWindowViewModel.cs'
$ui=Text 'src\MystTiq.Desktop\MainWindow.axaml'
$api=Text 'src\MystTiq.Desktop\Services\IMystTiqApiClient.cs'
$client=Text 'src\MystTiq.Desktop\Services\MystTiqApiClient.cs'
$pollDto=Text 'src\MystTiq.Desktop\Models\StatusPollingDto.cs'
$serverStatusDto=Text 'src\MystTiq.Desktop\Models\ServerStatusDto.cs'
$apiHostSource=Text 'src\MystTiq.HeadlessHost\LocalManagementApiHost.cs'
$release=Text 'scripts\Build-Release.ps1'
$build=Text 'Build.ps1'
$readme=Text 'README.md'
$road=Text 'docs\roadmap\PRODUCT_ROADMAP.md'
$discovery=Text 'src\MystTiq.Desktop\Services\MystTiqServiceDiscoveryService.cs'
$appComposition=Text 'src\MystTiq.Desktop\App.axaml.cs'
$getVersion=Text 'scripts\Get-ProjectVersion.ps1'
$validator=Text 'scripts\Validate-Release.ps1'
$headlessProgram=Text 'src\MystTiq.HeadlessHost\Program.cs'
$windowsLifecycle=Text 'src\MystTiq.Core\Services\WindowsServerLifecycleService.cs'
$windowsInspector=Text 'src\MystTiq.Core\Services\WindowsServerSessionInspector.cs'
$bootstrapper=Text 'src\MystTiq.Desktop\Services\LocalManagementBootstrapper.cs'
$healthDto=Text 'src\MystTiq.Desktop\Models\ApiHealthDto.cs'
$desktopBuild=Text 'scripts\Build-AvaloniaDesktop.ps1'
$headlessConfig=Text 'src\MystTiq.Core\Services\HeadlessConfigurationService.cs'
$headlessConfigModel=Text 'src\MystTiq.Core\Models\HeadlessConfiguration.cs'
$serviceStatusProvider=Text 'src\MystTiq.HeadlessHost\ManagementServiceStatusProvider.cs'
$appXaml=Text 'src\MystTiq.Desktop\App.axaml'
$mainWindowCode=Text 'src\MystTiq.Desktop\MainWindow.axaml.cs'
$activityService=Text 'src\MystTiq.HeadlessHost\HeadlessActivityLogService.cs'
$playerAdminService=Text 'src\MystTiq.HeadlessHost\HeadlessPalworldAdminService.cs'
$playerMetadataService=Text 'src\MystTiq.HeadlessHost\HeadlessPlayerMetadataService.cs'
$playerGuildService=Text 'src\MystTiq.HeadlessHost\HeadlessPlayerGuildExplorerService.cs'
$playerMetadataDtos=Text 'src\MystTiq.Desktop\Models\PlayerMetadataDtos.cs'
$worldExplorerService=Text 'src\MystTiq.HeadlessHost\HeadlessWorldExplorerService.cs'
$activityDtos=Text 'src\MystTiq.Desktop\Models\ActivityAdminDtos.cs'
$palworldConfigService=Text 'src\MystTiq.Core\Services\PalworldSettingsConfigurationService.cs'
$palworldConfigDtos=Text 'src\MystTiq.Desktop\Models\PalworldConfigurationDtos.cs'
$monitoringService=Text 'src\MystTiq.HeadlessHost\HeadlessMonitoringService.cs'
$parityMatrix=Text 'docs\GUI_PARITY_v0.4.10.0.md'
$updateFromDownloads=Text 'scripts\Install-LatestFullSourceFromDownloads.ps1'
$monitoringDtos=Text 'src\MystTiq.Desktop\Models\MonitoringDtos.cs'
$historyService=Text 'src\MystTiq.HeadlessHost\HeadlessHistoricalMetricsService.cs'
$historyChart=Text 'src\MystTiq.Desktop\Controls\ResourceHistoryChart.cs'
$worldDtos=Text 'src\MystTiq.Desktop\Models\WorldExplorerDtos.cs'
$environmentService=Text 'src\MystTiq.HeadlessHost\HeadlessEnvironmentChecklistService.cs'
$environmentDtos=Text 'src\MystTiq.Desktop\Models\EnvironmentChecklistDtos.cs'
$updateWrapper=Text 'Update-FromDownloads.ps1'
$rconService=Text 'src\MystTiq.Core\Services\PalworldRconService.cs'
$rconDtos=Text 'src\MystTiq.Desktop\Models\RconDtos.cs'


Check 'Versioning' 'Version is v0.4.10.0' ($props -match '<VersionPrefix>0\.4\.10\.0</VersionPrefix>' -and $vm -match 'Version => "v0\.4\.10\.0"')
Check 'PowerShell Safety' 'Current logic harness does not assign to reserved automatic Host variable' ((Text 'scripts\Test-v0.4.10.0-Logic.ps1') -notmatch '(?im)^\s*\$host\s*=')
Check 'Composition' 'Desktop remains Avalonia MVVM' ($ui -match 'x:DataType="vm:MainWindowViewModel"' -and $vm -match 'class MainWindowViewModel')
Check 'Windows Headless' 'api-run supports Windows and Linux instead of rejecting Windows' ($headlessProgram -match 'OperatingSystem\.IsWindows\(\)' -and $headlessProgram -match 'WindowsServerLifecycleService' -and $headlessProgram -notmatch 'Local API host in v0\.3\.0\.7 requires Linux')
Check 'Windows Headless' 'Windows lifecycle uses Core platform abstractions and verifies configured Palworld game port' ($windowsLifecycle -match 'IServerLifecycleService' -and $windowsLifecycle -match 'sessionInspector\.GetGuardedListeningPorts' -and $windowsLifecycle -match 'ports\.Contains\(expectedGamePort\)' -and $headlessProgram -match 'GetConfiguredGamePort')
Check 'Windows Headless' 'Windows session inspector discovers PalServer processes and guarded UDP listeners' ($windowsInspector -match 'Process\.GetProcesses' -and $windowsInspector -match 'netstat\.exe' -and $windowsInspector -match 'GetGuardedListeningPorts')
Check 'Service Status Abstraction' 'API service status is platform-neutral and does not pass a Linux service manager into Windows composition' ($serviceStatusProvider -match 'IManagementServiceStatusProvider' -and $serviceStatusProvider -match 'WindowsStandaloneManagementServiceStatusProvider' -and $apiHostSource -match 'IManagementServiceStatusProvider serviceStatusProvider')
Check 'Local Bootstrap' 'GUI can bootstrap packaged headless API without owning PalServer lifecycle' ($bootstrapper -match 'ILocalManagementBootstrapper' -and $bootstrapper -match 'api-run' -and $bootstrapper -notmatch 'PalServer\.exe' -and $vm -match '_localBootstrapper\.EnsureAvailableAsync')
Check 'Local Bootstrap' 'Legacy settings are never passed to the schema-v2 headless config loader' ($bootstrapper -match 'never pass settings-v2\.1\.json' -and $bootstrapper -match 'Path\.GetFileName\(persistentConfig\)\.Equals\("mysttiq\.json"')
Check 'Desktop Packaging' 'Windows/Linux desktop packages include matching self-contained headless sidecar' ($desktopBuild.Contains("Join-Path `$output 'headless'") -and $desktopBuild.Contains('dotnet publish $headlessProject') -and $desktopBuild.Contains('--self-contained true'))
Check 'Cross-platform Config' 'Headless configuration has Windows and Linux defaults with platform-aware absolute path validation' ($headlessConfig -match 'WindowsDefaultPath' -and $headlessConfig -match 'DefaultPath' -and $headlessConfig -match 'Path\.IsPathFullyQualified')
Check 'Lifecycle Launch' 'Default Windows PalServer launch is hidden and redirects Unreal logging to stdout' ($headlessConfigModel -match '-stdout' -and $headlessConfigModel -match '-FullStdOutLogOutput' -and $headlessConfigModel -match '-logformat=text' -and $windowsLifecycle -match 'CreateNoWindow = true' -and $windowsLifecycle -match 'WindowStyle = ProcessWindowStyle.Hidden' -and $windowsLifecycle -match 'RedirectStandardOutput = true' -and $windowsLifecycle -match 'RedirectStandardError = true')
Check 'Lifecycle Launch' 'Existing Windows configs cannot re-enable Unreal separate -log window' ($windowsLifecycle -match 'BuildHiddenConsoleArguments' -and $windowsLifecycle -match 'StringComparison.OrdinalIgnoreCase' -and $windowsLifecycle -match '"-log"' -and $windowsLifecycle -match '"-stdout"' -and $windowsLifecycle -match '"-FullStdOutLogOutput"')

Check 'Lifecycle Window Policy' 'Windows lifecycle reapplies proven v0.2 post-launch ShowWindow(SW_HIDE) policy to wrapper/child consoles' ($windowsLifecycle -match 'ApplyPostLaunchWindowPolicyAsync' -and $windowsLifecycle -match 'ShowWindow\(handle, SwHide\)' -and $windowsLifecycle -match 'DllImport\("user32.dll"\)' -and $windowsLifecycle -match 'for \(var attempt = 0; attempt < 40; attempt\+\+\)')
Check 'Dashboard Parity' 'Dashboard restores dense live v0.2-inspired world pulse health resource history activity log and online player surfaces' ($ui -match 'WORLD PULSE|DashboardWorldPulseText' -and $ui -match 'RESOURCE HISTORY' -and $ui -match 'LIVE ACTIVITY' -and $ui -match 'LIVE SERVER / MANAGER LOG' -and $ui -match 'ONLINE PLAYERS' -and $ui -match 'OVERALL HEALTH' -and $vm -match 'DashboardActivityLines' -and $vm -match 'MetricHistory')
Check 'Dashboard Polling' 'Dashboard live surfaces reuse aggregate poll state instead of introducing an independent polling loop' ($vm -match 'ApplyMetrics\(poll.Metrics\)' -and $vm -match 'ApplyLogs\(poll.LogTail\)' -and $vm -notmatch 'Dashboard.*Timer')
Check 'Polling Contract' 'Nullable lifecycle transition timestamp matches Core wire contract' ($serverStatusDto -match 'DateTimeOffset\? LastTransitionAt' -and $vm -match 'status\.LastTransitionAt is \{ \} lastTransitionAt' -and $vm -match 'FormatTime\(DateTimeOffset\? value\)')
Check 'Polling Contract' 'One aggregate status DTO owns periodic status payload' ($pollDto -match 'class StatusPollingDto' -and $pollDto -match 'ServerStatusDto Status' -and $pollDto -match 'ServiceStatusDto Service' -and $pollDto -match 'PlayersSnapshotDto Players' -and $pollDto -match 'RuntimeMetricsSnapshotDto Metrics' -and $pollDto -match 'LogTailSnapshotDto LogTail')
Check 'API Contract' 'ViewModel-facing API exposes aggregate polling method' ($api -match 'GetStatusPollingAsync')
Check 'API Client' 'Aggregate client calls exactly one polling endpoint' ($client -match 'GetStatusPollingAsync' -and $client -match '/api/v1/status/poll\?lines=')
Check 'Endpoint' 'Headless host exposes aggregate polling endpoint' ($apiHostSource -match 'MapGet\("/api/v1/status/poll"')
Check 'Endpoint' 'Polling endpoint samples lifecycle service players metrics and log tail' ($apiHostSource -match 'lifecycle\.GetStatusAsync' -and $apiHostSource -match 'serviceStatusProvider\.GetStatusAsync' -and $apiHostSource -match 'monitoring\.GetPlayersAsync' -and $apiHostSource -match 'monitoring\.GetMetricsAsync' -and $apiHostSource -match 'monitoring\.GetLogTail')
Check 'Endpoint' 'Independent async samples are awaited together' ($apiHostSource -match 'Task\.WhenAll\(statusTask, serviceTask, playersTask, metricsTask\)')
Check 'Behavior' 'Periodic timer uses aggregate poll instead of fan-out refresh' ($vm -match '_refreshTimer\.Tick' -and $vm -match 'await RefreshStatusPollingAsync\(\)' -and $vm -notmatch '_refreshTick % 2')
Check 'Behavior' 'Aggregate snapshot is applied to all live status surfaces' ($vm -match 'ApplyStatus\(snapshot\.Status\)' -and $vm -match 'ApplyServiceStatus\(snapshot\.Service\)' -and $vm -match 'ApplyPlayers\(snapshot\.Players\)' -and $vm -match 'ApplyMetrics\(snapshot\.Metrics\)' -and $vm -match 'ApplyLogs\(snapshot\.LogTail\)')
Check 'Status Bar' 'Global bottom status bar is present' ($ui -match 'StatusBarText' -and $ui -match 'StatusBarObservedText')
Check 'Status Bar' 'Busy work shows standard indeterminate animation' ($ui -match 'ProgressBar' -and $ui -match 'IsIndeterminate="True"' -and $ui -match 'IsVisible="\{Binding IsBusy\}"')
Check 'Status Bar' 'Busy state drives status text' ($vm -match 'StatusBarText = value \? "Working…"')
Check 'Workspace' 'Workspace is a real page, not a placeholder' ($vm -match 'IsWorkspacePage' -and $vm -notmatch 'IsPlaceholderPage => SelectedPage is NavigationPage\.Workspace')
Check 'Workspace' 'Workspace reads managed configuration paths' ($ui -match 'IsVisible="\{Binding IsWorkspacePage\}"' -and $ui -match 'ConfigServerRoot' -and $ui -match 'ConfigSteamCmdPath' -and $ui -match 'ConfigBackupRoot' -and $ui -match 'ConfigRuntimeRoot')
Check 'Workspace' 'Workspace refresh routes through ViewModel command to API configuration service' ($ui -match 'Refresh Workspace.+LoadConfigurationCommand' -and $vm -match '_api\.GetEditableConfigurationAsync')
Check 'Lifecycle' 'Start Stop Restart remain API-routed, not GUI-owned' ($vm -match '_api\.StartServerAsync' -and $vm -match '_api\.StopServerAsync' -and $vm -match '_api\.RestartServerAsync' -and $apiHostSource -match '/api/v1/server/start' -and $apiHostSource -match '/api/v1/server/stop' -and $apiHostSource -match '/api/v1/server/restart')
$desktopProject=Text 'src\MystTiq.Desktop\MystTiq.Desktop.csproj'
Check 'Platform Preservation' 'Desktop contains no WPF or Windows-only desktop dependency' ($desktopProject -notmatch 'Microsoft\.NET\.Sdk\.WindowsDesktop|<UseWPF>true</UseWPF>|net[0-9.]+-windows' -and $ui -notmatch 'System\.Windows\.(Controls|Window|Application)|PresentationFramework' -and $vm -notmatch 'System\.Windows\.(Controls|Window|Application)|Microsoft\.Win32')
Check 'Platform Preservation' 'System.Windows.Input ICommand remains allowed for cross-platform MVVM' ($vm -match 'System\.Windows\.Input' -or $vm -match '\bICommand\b')
Check 'Platform Preservation' 'Headless endpoint uses platform abstractions' ($apiHostSource -match 'ServerPathProfile\.ForCurrentPlatform' -and $apiHostSource -match 'ServerDistributionPlatformService\.ForCurrentPlatform')
Check 'Release Gate' 'Root build exposes version-selected LogicTests' ($build -match "'LogicTests'" -and $build -match 'Test-v\$v-Logic\.ps1')
Check 'Release Gate' 'Release workflow runs logic tests before packaging' ($release.IndexOf('Running v$version logic tests') -ge 0 -and $release.IndexOf('Running v$version logic tests') -lt $release.IndexOf('Creating portable package'))
Check 'Release Gate' 'Release workflow builds Windows and Linux headless plus desktop' ($release -match 'Build-WindowsHeadless\.ps1' -and $release -match 'Build-LinuxHeadless\.ps1' -and $release -match "Runtime 'win-x64'" -and $release -match "Runtime 'linux-x64'")
Check 'Release Gate' 'Runtime smoke runs after Windows desktop publish and before packaging' ($release -match 'Test-v\$version-RuntimeSmoke\.ps1' -and $release.IndexOf('Running Windows headless API runtime smoke') -gt $release.IndexOf('Building Avalonia desktop for Windows') -and $release.IndexOf('Running Windows headless API runtime smoke') -lt $release.IndexOf('Creating portable package'))

Check 'RunBuild Gate' '-RunBuild compiles shared desktop and headless targets for Windows and Linux' ($MyInvocation.MyCommand.Path -and (Text 'scripts\Test-v0.4.10.0-Logic.ps1') -match '-Action WindowsHeadless' -and (Text 'scripts\Test-v0.4.10.0-Logic.ps1') -match '-Action LinuxHeadless' -and (Text 'scripts\Test-v0.4.10.0-Logic.ps1') -match '-Action DesktopWindows' -and (Text 'scripts\Test-v0.4.10.0-Logic.ps1') -match '-Action DesktopLinux')
Check 'Documentation' 'README identifies v0.4.10.0 candidate and v0.4.9.1 baseline' ($readme -match 'Current release candidate: v0\.4\.10\.0' -and $readme -match 'Official baseline: v0\.4\.9\.1')
Check 'Documentation' 'Roadmap identifies v0.4.10.0 current candidate' ($road -match 'v0\.4\.10\.0.+Current Release Candidate')


Check 'Packaging' 'Current-version logic test exists at the exact release path' (Test-Path (Join-Path $root 'scripts\Test-v0.4.10.0-Logic.ps1') -PathType Leaf)
Check 'Version Wiring' 'Validator resolves version dynamically from Get-ProjectVersion' ($validator -match 'Get-ProjectVersion\.ps1' -and $getVersion -match 'Directory\.Build\.props' -and $build -match 'Test-v\$v-Logic\.ps1')
Check 'Discovery' 'Desktop has cross-platform LAN MystTiq service discovery' ($discovery -match 'NetworkInterface\.GetAllNetworkInterfaces' -and $discovery -match '/healthz' -and $discovery -match 'mysttiq-headless')
Check 'Discovery' 'Discovery is bounded and avoids broad subnet sweeps' ($discovery -match 'SemaphoreSlim\(32' -and $discovery -match 'MaxCandidatesPerInterface = 254' -and $discovery -match '169 && bytes\[1\] == 254')
Check 'Discovery Security' 'Relaxed TLS validation is isolated to health discovery; real API client retains normal validation/pinning' ($discovery -match 'ServerCertificateCustomValidationCallback' -and $client -match 'normal OS certificate validation remains authoritative' -and $client -match 'ServerCertificateSha256')
Check 'Composition' 'Discovery flows App -> ViewModel -> discovery service' ($appComposition -match 'MystTiqServiceDiscoveryService' -and $vm -match 'IMystTiqServiceDiscoveryService' -and $vm -match '_serviceDiscovery\.DiscoverAsync')
Check 'GUI Navigation' 'Top-level groups and expanded child rows use one standard navigation height' ($ui -match 'Expander Classes="navgroup"' -and $ui -match 'StackPanel Margin="0" Spacing="0"' -and (Text 'src\MystTiq.Desktop\App.axaml') -match 'Button\.navitem.+Height.+44' -and (Text 'src\MystTiq.Desktop\App.axaml') -match 'Expander\.navgroup.+MinHeight.+44')
Check 'GUI Navigation' 'Long navigation labels use compact standard font sizing' ((Text 'src\MystTiq.Desktop\App.axaml') -match 'Button\.navitem.+FontSize.+12')
Check 'GUI Navigation' 'Expanded child items are modestly indented without changing standard row height' ($ui -match 'Classes="navitem navchild"' -and (Text 'src\MystTiq.Desktop\App.axaml') -match 'Button\.navitem\.navchild.+Padding.+22,4,8,4' -and (Text 'src\MystTiq.Desktop\App.axaml') -match 'Button\.navitem.+Height.+44')
Check 'Branding' 'Avalonia desktop uses established MystTiq logo asset instead of temporary M glyph' ($ui -match 'PalworldServerManager\.png' -and $ui -notmatch 'Text="M" FontSize="34"' -and (Test-Path (Join-Path $root 'src\MystTiq.Desktop\Assets\PalworldServerManager.png') -PathType Leaf))
Check 'Branding' 'Window/application icon uses established MystTiq icon asset' ($ui -match 'Icon="/Assets/PalworldServerManager\.ico"' -and $desktopProject -match '<ApplicationIcon>Assets/PalworldServerManager\.ico</ApplicationIcon>' -and (Test-Path (Join-Path $root 'src\MystTiq.Desktop\Assets\PalworldServerManager.ico') -PathType Leaf))
Check 'GUI Discovery' 'Settings exposes LAN discovery and discovered-service selection' ($ui -match 'Discover LAN Services' -and $ui -match 'DiscoveredServices' -and $ui -match 'SelectedDiscoveredService')
Check 'Navigation Behavior' 'Opening operational pages triggers their ViewModel-backed refresh path' ($vm -match 'RefreshPageForNavigationAsync' -and $vm -match '(?s)NavigationPage\.Configuration.*?LoadConfigurationAsync' -and $vm -match '(?s)NavigationPage\.Backups.*?RefreshBackupsAsync' -and $vm -match '(?s)NavigationPage\.Inspector.*?RefreshWorldExplorerAsync' -and $vm -match '(?s)NavigationPage\.DiagnosticsCenter.*?RunNetworkDiagnosticsAsync')
Check 'Linux Packaging' 'Current Linux acceptance and production-readiness scripts exist' ((Test-Path (Join-Path $root 'scripts\Test-v0.4.10.0-LinuxAcceptance.sh') -PathType Leaf) -and (Test-Path (Join-Path $root 'scripts\Test-v0.4.10.0-ProductionReadiness.sh') -PathType Leaf))
Check 'Build UX' 'Windows desktop build auto-launches GUI only after successful publish and supports suppression' ((Text 'scripts\Build-AvaloniaDesktop.ps1') -match '\[switch\]\$NoLaunch' -and (Text 'scripts\Build-AvaloniaDesktop.ps1') -match 'Start-Process' -and (Text 'scripts\Build-AvaloniaDesktop.ps1').IndexOf('Start-Process') -gt (Text 'scripts\Build-AvaloniaDesktop.ps1').IndexOf('Avalonia desktop publish failed') -and $build -match 'NoGuiLaunch')
Check 'Testing UX' 'README includes full clean/unblock/validate/current-logic command sequence' ($readme -match 'Get-ChildItem \. -Recurse -Filter \*\.ps1 \| Unblock-File' -and $readme -match 'Test-v0\.4\.10\.0-Logic\.ps1')

Check 'Clean Gate' 'Clean stops only artifact-hosted MystTiq development processes before deleting artifacts' ($build -match 'Stop-ArtifactHostedProcesses' -and $build -match '\$processPath\.StartsWith\(\$artifactPrefix' -and $build -match 'MystTiq\.Desktop|mysttiq-server')
Check 'Clean Gate' 'Clean fails instead of falsely succeeding when artifacts remain' ($build -match 'Build clean failed: artifacts directory still exists' -and $build -match 'Remove-Item \$artifacts -Recurse -Force -ErrorAction Stop')

Check 'Runtime Smoke' 'Windows API runtime smoke script exists and checks health poll config and distribution endpoints' ((Test-Path (Join-Path $root 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -PathType Leaf) -and (Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match '/healthz' -and (Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match '/api/v1/status/poll' -and (Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match '/api/v1/config/editable' -and (Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match '/api/v1/rcon/status')

Check 'Connection Handshake' 'Health endpoint is versioned and identifies platform/API contract' ($apiHostSource -match 'apiVersion = 1' -and $apiHostSource -match 'version = typeof\(LocalManagementApiHost\)' -and $apiHostSource -match 'platform = OperatingSystem')
Check 'Connection Handshake' 'Desktop establishes connection through health plus the single aggregate poll endpoint' ($api -match 'GetHealthAsync' -and $client -match 'GetHealthAsync' -and $vm -match 'GetHealthAsync' -and $vm -match 'GetStatusPollingAsync\(profile, 120' -and $vm -notmatch 'var statusTask = _api\.GetStatusAsync\(profile, BearerToken\);\s*var serviceTask = _api\.GetServiceStatusAsync')
Check 'Connection Handshake' 'Desktop-owned sidecar forces loopback-only unauthenticated mode without weakening remote API rules' ($bootstrapper -match '--desktop-sidecar' -and $headlessProgram -match 'desktopSidecar' -and $headlessProgram -match 'Authentication = desktopSidecar.+Enabled = false' -and $headlessProgram -match 'Tls = desktopSidecar.+Enabled = false' -and $apiHostSource -match 'Non-loopback management API requires both authentication and TLS')
Check 'Connection Handshake' 'Occupied or incompatible loopback endpoint falls back to a private available port' ($bootstrapper -match 'FindAvailableLoopbackEndpoint' -and $bootstrapper -match 'apiVersion' -and $bootstrapper -match 'existing\.Reachable' -and $bootstrapper -match 'TcpListener\(IPAddress\.Loopback, 0\)')
Check 'Local Auto Connect' 'Discovery health metadata carries authentication state' ($discovery -match 'AuthenticationEnabled' -and $discovery -match 'TryGetProperty\("authentication"')
Check 'Local Auto Connect' 'Local profile prefers loopback service over LAN candidates' ($vm -match 'local profile must prefer loopback' -and $vm -match 'IPAddress\.IsLoopback')
Check 'Local Auto Connect' 'Unauthenticated loopback discovery immediately exercises real refresh connection path' ($vm -match '!preferred\.AuthenticationEnabled' -and $vm -match 'await RefreshAsync\(silent: false\)')
Check 'Remote Security' 'LAN discovery never auto-bypasses authentication' ($vm -match 'isLoopback && !preferred\.AuthenticationEnabled' -and $client -match 'AuthenticationHeaderValue\("Bearer"')
Check 'Tray Lifecycle' 'Application uses Avalonia TrayIcon with native Show/lifecycle/safe-force-GUI-only exit controls' ($appXaml -match '<TrayIcon ' -and $appXaml -match 'NativeMenuItem Header="Show MystTiq"' -and $appXaml -match 'Start Palworld Server' -and $appXaml -match 'Stop Palworld Server' -and $appXaml -match 'Safe Exit' -and $appXaml -match 'Force Exit' -and $appXaml -match 'Exit GUI Only')
Check 'Tray Lifecycle' 'Closing the main window hides to tray and explicit exit owns shutdown' ($appComposition -match 'ShutdownMode\.OnExplicitShutdown' -and $mainWindowCode -match 'Closing \+= MainWindow_Closing' -and $mainWindowCode -match 'HideMainWindowToTray' -and $appComposition -match 'desktopLifetime\?\.Shutdown')
Check 'Tray Lifecycle' 'Only the sidecar started by this GUI session can be killed from tray' ($bootstrapper -match 'ownedSidecarProcessId' -and $bootstrapper -match 'ownedSidecarExecutable' -and $bootstrapper -match 'StopOwnedSidecarAsync' -and $bootstrapper -match 'Path\.GetFullPath\(actualPath\)\.Equals')
Check 'Lifecycle UX' 'API connectivity is tracked independently from display status so failed operations remain retryable' ($vm -match 'ManagementApiConnected' -and $vm -match 'StartCommand = new AsyncCommand\(StartServerAsync.+ManagementApiConnected' -and $vm -match 'ConnectionState = result\.Success \? "Connected" : "Operation failed"')
Check 'Lifecycle UX' 'Start performs local backend recovery and server-distribution preflight before lifecycle mutation' ($vm -match 'EnsureManagementConnectionForLifecycleAsync' -and $vm -match '_localBootstrapper\.EnsureAvailableAsync' -and $vm -match 'GetServerDistributionStatusAsync' -and $vm -match 'Start blocked: PalServer executable was not found')
Check 'Lifecycle UX' 'Lifecycle result is visible on the GUI instead of failing silently' ($vm -match 'LifecycleStatusText' -and $ui -match 'Text="\{Binding LifecycleStatusText\}"')
Check 'Page Parity' 'Previously shared navigation destinations expose distinct page-specific views' ($vm -match 'IsServerSetupPage' -and $vm -match 'IsUpdateCenterPage' -and $vm -match 'IsBasesPage' -and $vm -match 'IsGuildsPage' -and $vm -match 'IsConsolePage' -and $vm -match 'IsActivityAuditPage' -and $vm -match 'IsModDashboardPage' -and $vm -match 'IsModLibraryPage' -and $vm -match 'IsUe4ssPage')
Check 'Page Parity' 'UI renders distinct legacy-inspired headings for setup/update, bases/guilds, console/audit, and MOD/UE4SS pages' (($ui -match 'Text="Server Setup"' -or $ui -match 'Text="SERVER ENVIRONMENT"') -and $ui -match 'Text="Update Center"' -and $ui -match 'Text="Base Manager"' -and $ui -match 'Text="Guild Administration"' -and $ui -match 'Text="Live Console"' -and $ui -match 'Text="Activity &amp; Audit"' -and $ui -match 'Text="MOD Dashboard"' -and $ui -match 'Text="MOD Library"' -and $ui -match 'Text="UE4SS Runtime"')
Check 'Runtime Smoke' 'Isolated start-route smoke cannot launch the user PalServer and verifies a safe 424 response' ((Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match 'missing-server' -and (Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match '/api/v1/server/start' -and (Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match 'StatusCode -ne 424')

Check 'Hover UX' 'Meaningful hover information remains while generic self-evident tooltip text is removed' ($ui -match 'ToolTip.Tip=' -and $appXaml -match 'ToolTip.ShowDelay' -and $ui -notmatch 'ToolTip.Tip="Run or open ' -and $ui -notmatch 'ToolTip.Tip="Choose an option from this selection\.' -and $ui -notmatch 'ToolTip.Tip="Select an item to inspect its details or available actions\.')
Check 'Palworld Configuration' 'Configuration page edits active PalWorldSettings through View -> ViewModel -> API -> endpoint -> Core' ($ui -match 'Server Configuration' -and $ui -match 'FilteredPalworldSettings' -and $vm -match 'LoadPalworldConfigurationAsync' -and $vm -match 'SavePalworldConfigurationAsync' -and $api -match 'GetPalworldConfigurationAsync' -and $api -match 'SavePalworldConfigurationAsync' -and $client -match '/api/v1/palworld/config' -and $apiHostSource -match '/api/v1/palworld/config' -and $palworldConfigService -match 'OptionSettings=\(')
Check 'Palworld Configuration' 'Saving PalWorldSettings creates rollback copy and preserves full active setting list' ($palworldConfigService -match 'ConfigBackups' -and $palworldConfigService -match 'timestamped rollback copy' -and $palworldConfigService -match 'string.Join\(","')
Check 'Lifecycle Port' 'PalServer readiness uses configured PublicPort instead of fixed UDP 8211' ($palworldConfigService -match 'PublicPort' -and $headlessProgram -match 'configuredGamePort' -and $windowsLifecycle -match 'expectedGamePort' -and (Text 'src\MystTiq.Core\Services\LinuxServerLifecycleService.cs') -match 'expectedGamePort')
Check 'Page Parity Audit' 'v0.2.16.4 page-by-page parity matrix explicitly tracks migrated partial and missing functionality' ($parityMatrix -match 'Crash Analyzer.+Not migrated' -and $parityMatrix -match 'Live Console & RCON.+Migrated / acceptance pending' -and $parityMatrix -match 'Configuration.+Migrated' -and $parityMatrix -match 'Recovery.+Not migrated')
Check 'Avalonia XAML Safety' 'Property elements do not carry normal control attributes' ($ui -notmatch '<(?:ListBox|ComboBox)\.(?:ItemTemplate|ContextMenu)\s+[^>]*ToolTip\.Tip=')
Check 'Avalonia XAML Safety' 'ListBox uses supported item-container stretching instead of unsupported HorizontalContentAlignment' ($ui -notmatch '<ListBox[^>]*HorizontalContentAlignment=' -and $ui -match '<Style Selector="ListBoxItem">' -and $ui -match '<Setter Property="HorizontalAlignment" Value="Stretch"/?>')
Check 'Player Context Actions' 'Players expose right-click administration and API wiring' ($ui -match 'ListBox.ContextMenu' -and $ui -match 'Kick Player' -and $ui -match 'Ban Player' -and $ui -match 'Whisper.+BACKEND REQUIRED' -and $ui -match 'Give Item.+BACKEND REQUIRED' -and $vm -match 'RunSelectedPlayerAdminActionAsync' -and $client -match 'RunPlayerAdminActionAsync' -and $apiHostSource -match '/api/v1/players/\{playerId\}/action')
Check 'Player Context Actions' 'Unsupported vanilla actions are capability-gated instead of faking success' ($playerAdminService -match 'whisper.+promote.+give-item' -and $playerAdminService -match 'Vanilla Palworld' -and $apiHostSource -match '422UnprocessableEntity')
Check 'Activity Audit' 'Headless backend persists activity and audit logs and exposes them to the GUI' ($activityService -match 'MystTiq-Activity.log' -and $activityService -match 'MystTiq-Audit.jsonl' -and $apiHostSource -match '/api/v1/activity/tail' -and $api -match 'GetActivityLogTailAsync' -and $vm -match 'RefreshActivityAsync' -and $ui -match 'MystTiq Activity / Audit Log')
Check 'Console Capture' 'Windows lifecycle captures PalServer stdout and stderr when MystTiq launches the server' ($windowsLifecycle -match 'RedirectStandardOutput = true' -and $windowsLifecycle -match 'RedirectStandardError = true' -and $windowsLifecycle -match 'MystTiq-PalServer-Console.log')
Check 'Console Capture' 'Live Console combines MystTiq redirected output, Pal.log and available server-mod logs' ($monitoringService -match 'ResolveConsoleSources' -and $monitoringService -match 'MystTiq-PalServer-Console\.log' -and $monitoringService -match 'Pal\.log' -and $monitoringService -match 'AdminCommands server log')
Check 'Console Capture' 'Windows default arguments do not request Unreal separate -log window' ($headlessConfigModel -notmatch '\["-useperfthreads", "-NoAsyncLoadingThread", "-UseMultithreadForDS", "-log",' -and $headlessConfigModel -match '-stdout' -and $headlessConfigModel -match '-FullStdOutLogOutput')
Check 'World Discovery' 'World explorer avoids recursive backup false positives' ($worldExplorerService -match 'EnumerateCanonicalWorldDirectories' -and $worldExplorerService -notmatch 'EnumerateFiles\(\s*paths.SaveRoot,\s*"Level.sav",\s*SearchOption.AllDirectories')
Check 'World Inspector UX' 'World ID is fully displayed while a short nickname is available' ($ui -match 'Full canonical active World ID' -and $ui -match 'Text="\{Binding Nickname\}"' -and $ui -match 'Text="\{Binding WorldId\}"' -and (Text 'src\MystTiq.Desktop\Models\WorldExplorerDtos.cs') -match 'public string Nickname')
Check 'Runtime Smoke' 'Runtime smoke exercises player capability gating metadata persistence and audit privacy' ((Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match 'Player administration route is live' -and (Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match 'Player notes and warnings persist' -and (Text 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -match 'without private bodies')

Check 'Deployment UX' 'Latest FullSource updater selects newest Downloads package and validates archive before replacement' ($updateFromDownloads -match 'MystTiqPalworldServer_v\*_FullSource\*\.zip' -and $updateFromDownloads -match 'Sort-Object LastWriteTimeUtc -Descending' -and $updateFromDownloads -match 'Assert-SafeArchiveEntries' -and $updateFromDownloads -match 'missing \$required')
Check 'Deployment UX' 'Updater cleans running development processes before clearing target tree' ($updateFromDownloads -match '& \$cleanScript Clean' -and $updateFromDownloads.IndexOf('& $cleanScript Clean') -lt $updateFromDownloads.IndexOf('Clearing target source tree') -and $updateFromDownloads -match 'Get-ChildItem -LiteralPath \$TargetPath -Force')
Check 'Deployment UX' 'Updater copies staged FullSource and runs the complete current-release gate by default' ($updateFromDownloads -match 'Expand-Archive' -and $updateFromDownloads -match 'Copy-Item' -and $updateFromDownloads -match 'Get-ProjectVersion\.ps1' -and $updateFromDownloads -match 'Test-CurrentRelease\.ps1' -and $updateFromDownloads -match 'SkipBuild')
Check 'Dashboard UX' 'Dashboard has only one heading and restores server name/description footer' ($ui -notmatch '<TextBlock Text="Dashboard" FontSize="24"' -and $ui -match 'DashboardServerNameText' -and $ui -match 'DashboardServerDescriptionText')
Check 'Dashboard UX' 'CPU and memory meters remain live while Resource History owns the full graph' ($ui -match 'Value="{Binding CpuPercentValue}"' -and $ui -match 'Value="{Binding MemoryScaleValue}"' -and $ui -match 'ResourceHistoryChart' -and $monitoringDtos -match 'HistoricalMetricPointDto')
Check 'Dashboard UX' 'Active World shows nickname, full canonical ID and clipboard action' ($ui -match 'DashboardWorldNicknameText' -and $ui -match 'DashboardWorldText' -and $ui -match 'CopyActiveWorldId_Click' -and $mainWindowCode -match 'SetTextAsync\(vm\.ActiveWorldIdText\)')
Check 'World Pulse' 'Aggregate status poll carries authoritative world clock/save, backup and Palworld identity support data' ($apiHostSource -match 'ExploreDashboard\(\)' -and $apiHostSource -match 'backupInventory' -and $apiHostSource -match 'palworldSettings' -and $pollDto -match 'WorldExplorerSnapshotDto World' -and $pollDto -match 'BackupInventoryDto BackupInventory' -and $pollDto -match 'PalworldConfigurationSnapshotDto PalworldSettings' -and $worldExplorerService -match 'GameDateTimeTicks')
Check 'World Pulse' 'Dashboard renders distinct World Pulse day/session/save/backup information' ($ui -match 'WORLD PULSE' -and $ui -match 'DashboardWorldClockText' -and $ui -match 'DashboardPulseSaveText' -and $ui -match 'DashboardPulseBackupText' -and $vm -match 'ApplyDashboardSupport')
Check 'Console UX' 'Live console is green and combines lifecycle stdout Pal.log and optional mod log detail' ($ui -match '#58E36B' -and $monitoringService -match 'MystTiq redirected stdout/stderr \+ lifecycle' -and $monitoringService -match 'Pal\.log' -and $monitoringService -match 'AdminCommands')
Check 'Sidebar UX' 'Persistent server status uses wrapped management text rather than overlapping label/value columns' ($ui -match 'Text="MANAGEMENT"' -and $ui -match 'Text="\{Binding ServiceState\}" FontSize="10" TextWrapping="Wrap"' -and $ui -notmatch 'Text="MystTiq Service" Classes="muted"')

Check 'Server Setup Parity' 'Server Setup restores v0.2-style environment health checklist and operation monitor' ($ui -match 'SERVER ENVIRONMENT' -and $ui -match 'ENVIRONMENT HEALTH' -and $ui -match 'EnvironmentItems' -and $ui -match 'SERVER OPERATIONS' -and $ui -match 'OPERATION MONITOR' -and $ui -match 'INSTALL MISSING' -and $ui -match 'VERIFY FILES')
Check 'Server Setup Wiring' 'Environment checklist flows View -> ViewModel -> API -> endpoint -> headless platform inspection' ($vm -match 'RefreshEnvironmentAsync' -and $api -match 'GetEnvironmentChecklistAsync' -and $client -match '/api/v1/server/environment' -and $apiHostSource -match '/api/v1/server/environment' -and $environmentService -match 'Steam Client' -and $environmentService -match 'Palworld Dedicated Server' -and $environmentService -match 'Backup Storage')
Check 'Server Setup Behavior' 'Install missing can provision SteamCMD before Palworld distribution update' ((Text 'src\MystTiq.HeadlessHost\HeadlessServerDistributionService.cs') -match 'ProvisionSteamCmdAsync' -and (Text 'src\MystTiq.HeadlessHost\HeadlessServerDistributionService.cs') -match 'SteamCmdPackageUri' -and (Text 'src\MystTiq.HeadlessHost\HeadlessServerDistributionService.cs') -match 'ExtractSteamCmdPackage')
Check 'Server Setup Capability Truth' 'Environment rows carry action support/reason and unsupported mutations are disabled in the View' ($environmentDtos -match 'ActionSupported' -and $environmentDtos -match 'UnavailableReason' -and $ui -match 'IsEnabled="{Binding ActionSupported}"' -and $ui -match 'ActionDisplay' -and $environmentService -match 'BACKEND REQUIRED')
Check 'Server Setup Capability Truth' 'ViewModel refuses unsupported environment actions instead of falling through to generic verify' ($vm -match 'if \(!item\.ActionSupported\)' -and $vm -match 'SetupOperationState = "BACKEND REQUIRED"' -and $vm -match 'cannot be changed from the GUI yet')
Check 'Dashboard Reconstruction' 'Legacy card actions and health strip use real commands while Cleanup capability remains explicit' ($ui -match 'CommandParameter="Inspector"' -and $ui -match 'CommandParameter="Players"' -and $ui -match 'CommandParameter="Guilds"' -and $ui -match 'CommandParameter="ModDashboard"' -and $ui -match 'Command="{Binding CreateBackupCommand}"' -and $ui -match 'DashboardRestText' -and $ui -match 'DashboardRconText' -and $ui -match 'BACKEND REQUIRED: cleanup')
Check 'Server Setup Visual Parity' 'Server Setup owns the historical banner and hides the generic duplicate page header' ($ui -match 'Text="Server Setup" FontSize="25"' -and $ui -match 'Install, verify, and maintain the components required to run your Palworld dedicated server' -and $vm -match 'ShowGlobalPageHeader => SelectedPage != NavigationPage.ServerSetup')
Check 'Navigation Selection' 'Every navigation destination binds selected-state highlight to ViewModel page state' ($ui -match 'Classes\.active="\{Binding IsDashboardPage\}"' -and $ui -match 'Classes\.active="\{Binding IsServerSetupPage\}"' -and $ui -match 'Classes\.active="\{Binding IsPlayersPage\}"' -and $ui -match 'Classes\.active="\{Binding IsSettingsPage\}"' -and $appXaml -match 'Button\.navitem\.active')
Check 'Navigation Selection' 'Parent navigation group follows programmatic page changes so the selected child remains visible' ($ui -match 'IsExpanded="\{Binding IsServerGroupSelected, Mode=OneWay\}"' -and $ui -match 'IsExpanded="\{Binding IsWorldGroupSelected, Mode=OneWay\}"' -and $vm -match 'RaisePropertyChanged\(nameof\(IsServerGroupSelected\)\)')
Check 'Live Activity' 'Dashboard Live Activity is sourced from console/log tail rather than repeated status polling messages' ($vm -match 'DashboardActivityLines\.Clear\(\)' -and $vm -match 'snapshot\.Lines.*TakeLast\(8\)' -and $vm -notmatch 'var activity = .*ServerState')
Check 'Console Startup' 'Windows lifecycle writes launch path arguments PID readiness and stop events into the in-app console stream' ($windowsLifecycle -match 'AppendLifecycleConsoleLine' -and $windowsLifecycle -match 'Launching:' -and $windowsLifecycle -match 'Arguments:' -and $windowsLifecycle -match 'UDP .* verified' -and $windowsLifecycle -match 'stopped cleanly')
Check 'Deployment UX' 'Root updater relocates destructive helper outside source tree before replacement' ($updateWrapper -match 'GetTempPath' -and $updateWrapper -match 'Copy-Item' -and $updateWrapper -match 'tempHelper')
Check 'Deployment UX' 'One updater command proceeds through complete build/logic/runtime gate when installation succeeds' ($updateFromDownloads -match 'complete current-release gate' -and $updateFromDownloads -match 'Test-CurrentRelease\.ps1' -and $updateFromDownloads -match 'SkipBuild')
Check 'Parity Iteration' 'Current parity matrix enumerates the legacy window set rather than treating page titles as completion' ($parityMatrix -match 'Server Setup' -and $parityMatrix -match 'World Inspector' -and $parityMatrix -match 'Recovery' -and $parityMatrix -match 'Notifications' -and $parityMatrix -match 'Diagnostics Center')

Check 'Resource History' 'Dashboard restores v0.2-style graph, range selector and average/peak summaries' ($ui -match 'RESOURCE HISTORY' -and $ui -match 'HistoryRanges' -and $ui -match 'SelectedHistoryRange' -and $ui -match 'ResourceHistoryChart' -and $ui -match 'HistoryCpuSummary' -and $ui -match 'HistoryMemorySummary')
Check 'Resource History' 'Historical metrics persist in the headless runtime without creating a second polling loop' ($historyService -match 'MinimumSampleInterval' -and $historyService -match 'metrics.json' -and $apiHostSource -match 'historicalMetrics.Record' -and $apiHostSource -match '/api/v1/history' -and $vm -match 'GetHistoricalMetricsAsync' -and $vm -notmatch 'DispatcherTimer.*history')
Check 'Resource History' 'Custom Avalonia chart draws CPU and memory lines using DrawingContext' ($historyChart -match 'override void Render' -and $historyChart -match 'DrawLine' -and $historyChart -match '#54B8FF' -and $historyChart -match '#B58BFF')
Check 'Dashboard Containment' 'CPU/memory meters and history chart are clipped to their owning cards' ($ui -match 'ClipToBounds="True"' -and $ui -match 'CpuPercentValue' -and $ui -match 'MemoryScaleValue' -and $historyChart -match 'PushClip' -and $historyChart -match 'const double inset = 2')
Check 'Runtime Metrics' 'Headless monitoring aggregates managed PalServer process CPU memory and threads' ($monitoringService -match 'status.Processes.Select' -and $monitoringService -match 'workingSet \+=' -and $monitoringService -match 'threads \+=' -and $monitoringService -match 'aggregated across')

Check 'GUI Restoration Roadmap' 'Versioned roadmap starts at v0.4.7.0 and requires old visual -> handler intent -> ViewModel -> API client -> route -> headless service tracing' ((Text 'docs\GUI_RESTORATION_ROADMAP_v0.4.7.0_PLUS.md') -match 'v0\.4\.7\.0' -and (Text 'docs\GUI_RESTORATION_ROADMAP_v0.4.7.0_PLUS.md') -match 'old visual/control.*old handler intent.*current ViewModel command.*current API client.*current API route.*current headless service')
Check 'GUI Restoration Roadmap' 'Missing state-changing functionality is explicitly BACKEND REQUIRED and dangerous world operations use mandatory safety sequence' ((Text 'docs\GUI_RESTORATION_ROADMAP_v0.4.7.0_PLUS.md') -match 'BACKEND REQUIRED' -and (Text 'docs\GUI_RESTORATION_ROADMAP_v0.4.7.0_PLUS.md') -match 'Preview.*Safety Backup.*Server-side Transaction.*Validate.*Journal/Audit.*Refresh GUI')
Check 'GUI Restoration References' 'Reconstruction guide, historical event inventory and functional crosswalk ship with the source' ((Test-Path (Join-Path $root 'docs\reconstruction\MystTiq_GUI_Reconstruction_Guide.md')) -and (Test-Path (Join-Path $root 'docs\reconstruction\MystTiq_v0.2.16.4_GUI_Event_Inventory.csv')) -and (Test-Path (Join-Path $root 'docs\reconstruction\MystTiq_GUI_Functional_Crosswalk_v0.2.16.4_to_v0.4.6.3.csv')))

Check 'Configuration Parity' 'Simple and Advanced views share the same authoritative filtered settings collection' ($ui -match 'Simple Settings' -and $ui -match 'Advanced Settings' -and $ui -match 'FilteredPalworldSettings' -and $vm -match 'SetConfigurationView' -and $vm -match 'ApplyPalworldConfigurationFilter')
Check 'Configuration Parity' 'Search and category filters are client-side presentation only' ($ui -match 'ConfigSearchText' -and $ui -match 'PalworldConfigCategories' -and $vm -match 'ConfigSearchText' -and $vm -match 'SelectedConfigCategory' -and $vm -notmatch '/api/v1/palworld/config/search')
Check 'Configuration Presets' 'Historical Official Balanced and Relaxed QoL presets are restored without identity/port mutation' ($vm -match 'Official / Vanilla' -and $vm -match 'Balanced QoL' -and $vm -match 'Relaxed QoL' -and $vm -match 'DayTimeSpeedRate' -and $vm -match 'CollectionDropRate' -and $vm -notmatch 'p\["ServerName"\]' -and $vm -notmatch 'p\["PublicPort"\]')
Check 'Configuration Dirty State' 'Setting edits track original value, dirty state and validation before API save' ($palworldConfigDtos -match 'INotifyPropertyChanged' -and $palworldConfigDtos -match 'OriginalValue' -and $palworldConfigDtos -match 'IsDirty' -and $vm -match 'PalworldConfigDirtyText' -and $vm -match 'ValidatePalworldConfiguration' -and $vm -match 'PalworldConfigHasValidationErrors')
Check 'Configuration Import Export' 'Avalonia StorageProvider handles local import/export while server persistence remains API routed' ($mainWindowCode -match 'StorageProvider\.OpenFilePickerAsync' -and $mainWindowCode -match 'StorageProvider\.SaveFilePickerAsync' -and $vm -match 'ImportPalworldConfigurationJson' -and $vm -match 'ExportPalworldConfigurationJson' -and $vm -match '_api\.SavePalworldConfigurationAsync' -and $mainWindowCode -notmatch 'PalWorldSettings\.ini')
Check 'Configuration Safety' 'Import does not write server files and save remains rollback-backed in Core' ($vm -match 'Save Changes to write the server configuration' -and $palworldConfigService -match 'ConfigBackups|backup' -and $client -match 'PutAsJsonAsync\("/api/v1/palworld/config"')
Check 'Configuration Preservation' 'Advanced configuration retains unknown/custom OptionSettings returned by backend' ($vm -match 'foreach \(var setting in snapshot\.Settings\)' -and $ui -match 'Unknown settings are preserved' -and $palworldConfigService -match 'OptionSettings')

# In-memory presentation contract for the filtering rules (no server required).
$configSamples=@(
 [pscustomobject]@{Name='ServerName';DisplayName='Server Name';Category='Identity'},
 [pscustomobject]@{Name='PublicPort';DisplayName='Public Port';Category='Network'},
 [pscustomobject]@{Name='DropItemMaxNum';DisplayName='Drop Item Maximum';Category='Advanced'}
)
$configSearch='port';$configCategory='Network'
$configFiltered=@($configSamples|Where-Object{($_.Name -match $configSearch -or $_.DisplayName -match $configSearch) -and $_.Category -eq $configCategory})
Check 'Configuration Behavioral Contract' 'Search plus category filtering returns only matching settings' ($configFiltered.Count -eq 1 -and $configFiltered[0].Name -eq 'PublicPort')

# In-memory behavioral contract: verify the wire payload shape expected by the DTO/client without a running server.
$sample = '{"observedAt":"2026-08-26T12:00:00Z","status":{"phase":1,"ready":false,"lastTransitionAt":null},"service":{"installed":true,"enabled":true,"activeState":"active"},"players":{"available":true,"onlineCount":3,"players":[]},"metrics":{"available":true,"cpuPercent":12.5,"workingSetBytes":104857600,"threadCount":42},"logTail":{"available":true,"fileName":"PalWorldSettings.log","lines":["ready"]}}' | ConvertFrom-Json
Check 'Global Card Containment' 'Shared card/status styles clip children and wrap card text so dynamic content cannot paint outside cards' ($appXaml -match 'Style Selector="Border.card"' -and $appXaml -match 'ClipToBounds" Value="True"' -and $appXaml -match 'Border.card TextBlock' -and $appXaml -match 'TextWrapping" Value="Wrap"' -and $appXaml -match 'Border.card Grid' -and $appXaml -match 'Border.statuscard')
Check 'Console Parity' 'Console restores severity/category/search/hide-REST/pause/clear/export presentation controls' ($ui -match 'ConsoleSeverityOptions' -and $ui -match 'ConsoleCategoryOptions' -and $ui -match 'ConsoleSearchText' -and $ui -match 'HideRoutineRest' -and $ui -match 'PauseConsoleCommand' -and $ui -match 'ClearConsoleViewCommand' -and $ui -match 'ExportConsole_Click' -and $vm -match 'ApplyConsoleFilter' -and $mainWindowCode -match 'MystTiq-Console-')
Check 'Console Behavior' 'Pause and Clear View affect presentation only, not persistent backend log capture' ($vm -match 'if \(ConsolePaused\) return' -and $vm -match 'FilteredLogLines\.Clear\(\)' -and $vm -notmatch 'ClearConsoleView.*File\.Delete' -and $monitoringService -match 'ResolveConsoleSources')
Check 'RCON Wiring' 'RCON flows View -> ViewModel -> API client -> headless route -> Core service' ($ui -match 'RCON Doctor' -and $ui -match 'RconSendCommand' -and $vm -match 'RunRconDoctorAsync' -and $vm -match 'SendRconCommandAsync' -and $api -match 'RunRconDoctorAsync' -and $api -match 'SendRconCommandAsync' -and $client -match '/api/v1/rcon/doctor' -and $client -match '/api/v1/rcon/command' -and $apiHostSource -match '/api/v1/rcon/status' -and $apiHostSource -match '/api/v1/rcon/doctor' -and $apiHostSource -match '/api/v1/rcon/command' -and $rconService -match 'class PalworldRconService')
Check 'RCON Security' 'AdminPassword remains server-side and desktop RCON DTOs never expose credentials' ($rconService -match 'AdminPassword' -and $rconService -match '127\.0\.0\.1' -and $rconDtos -notmatch 'AdminPassword' -and $rconDtos -notmatch 'string Password' -and $rconDtos -notmatch 'PasswordValue' -and $ui -match 'never sends it to the GUI')
Check 'RCON Capability Truth' 'RCON doctor checks enabled/password/TCP/authentication and command input is bounded' ($rconService -match 'RCONEnabled' -and $rconService -match 'PasswordConfigured' -and $rconService -match 'TcpClient' -and $rconService -match 'Authenticated' -and $rconService -match 'normalized\.Length > 2048' -and $rconService -match 'CancelAfter')
# In-memory console-filter behavioral contract: routine status polling is hidden while errors remain searchable.
$consoleSamples=@('[MYSTTIQ] GET /api/v1/status/poll HTTP 200','[PALSERVER] startup complete','[PALSERVER] ERROR failed to bind')
$consoleVisible=@($consoleSamples | Where-Object { $_ -notmatch '/api/v1/status/poll' -and $_ -match 'ERROR' })
Check 'Console Behavioral Contract' 'Hide routine REST plus severity filtering preserves only matching visible rows' ($consoleVisible.Count -eq 1 -and $consoleVisible[0] -match 'failed to bind')
Check 'RCON Boundary' 'Desktop owns no RCON transport code and headless Core owns network transport' ($vm -notmatch 'using System\.Net\.Sockets|new\s+(?:TcpClient|Socket)\b' -and $client -notmatch 'using System\.Net\.Sockets|new\s+(?:TcpClient|Socket)\b' -and $rconService -match 'using System\.Net\.Sockets' -and $rconService -match 'new TcpClient')
Check 'RCON Audit Safety' 'RCON audit records command verb without persisting full command arguments' ($apiHostSource -match 'commandVerb' -and $apiHostSource -match "Split\(' ', 2" -and $apiHostSource -notmatch 'RCON command: \{result\.Command\}')
Check 'Players Parity' 'Player page restores search view/admin filters live/known directory details save discovery and CSV export' ($ui -match 'PlayerSearchText' -and $ui -match 'PlayerViewFilters' -and $ui -match 'PlayerAdminFilters' -and $ui -match 'FilteredPlayerRecords' -and $ui -match 'SelectedPlayerRecord\.Evidence' -and $ui -match 'Discover Saves' -and $ui -match 'ExportPlayersCsv_Click' -and $mainWindowCode -match 'MystTiq-Players-' -and $vm -match 'ExportVisiblePlayersCsv')
Check 'Players Composition' 'Player metadata traces View -> ViewModel -> API client -> route -> headless service' ($ui -match 'SavePlayerNotesCommand' -and $ui -match 'AddPlayerWarningCommand' -and $vm -match '_api\.SavePlayerNotesAsync' -and $vm -match '_api\.AddPlayerWarningAsync' -and $api -match 'GetPlayerMetadataAsync' -and $api -match 'SavePlayerNotesAsync' -and $api -match 'AddPlayerWarningAsync' -and $client -match '/api/v1/players/\{id\}/metadata' -and $client -match '/api/v1/players/\{id\}/warnings' -and $apiHostSource -match '/api/v1/players/\{playerId\}/metadata' -and $apiHostSource -match '/api/v1/players/\{playerId\}/warnings' -and $apiHostSource -match 'HeadlessPlayerMetadataService')
Check 'Players Remote Safety' 'Live-only identities are composed server-side and GUI does not inspect remote save paths' ($playerGuildService -match 'allPlayerIds\.Add\(id\)' -and $playerGuildService -match 'Currently online via Palworld REST' -and $vm -match '_api\.GetPlayerGuildExplorerAsync' -and $vm -notmatch 'Directory\.EnumerateFiles.*Player|GetFiles.*Players')
Check 'Players Stable Selection' 'Refresh and filtering restore selection by stable player ID' ($vm -match 'var selectedId = SelectedPlayerRecord\?\.PlayerId' -and $vm -match 'string\.Equals\(x\.PlayerId, selectedId, StringComparison\.OrdinalIgnoreCase\)')
Check 'Players Capability Truth' 'Kick/Ban require live selection and unsupported player commands cannot execute' ($vm -match 'SelectedPlayerRecord\?\.Online == true' -and ([regex]::Matches($vm,'RunSelectedPlayerAdminActionAsync\("(?:whisper|promote|give-item)"\), \(\) => false').Count -eq 3) -and $ui -match 'Whitelist.+BACKEND REQUIRED' -and $ui -match 'Temporary Ban.+BACKEND REQUIRED' -and $ui -match 'Unban.+BACKEND REQUIRED' -and $ui -match 'Remove Admin.+BACKEND REQUIRED')
Check 'Players Metadata Safety' 'Metadata validates IDs and bounded text and writes atomically' ($playerMetadataService -match '\^\[A-Za-z0-9:_-\]\{1,128\}\$' -and $playerMetadataService -match 'NormalizeText\(notes, 4000' -and $playerMetadataService -match 'NormalizeText\(message, 1000' -and $playerMetadataService -match 'File\.Move\(temp, path, true\)' -and $playerMetadataService -match 'TakeLast\(100\)')
Check 'Players Audit Privacy' 'Every metadata mutation is audited without copying note or warning bodies into audit detail' ($playerMetadataService -match 'Player notes updated' -and $playerMetadataService -match 'characters=\{value\.Length\}' -and $playerMetadataService -match 'Player warning added' -and $playerMetadataService -match 'warningCount=\{warnings\.Length\}' -and $playerMetadataService -notmatch 'activity\.Record\([^\r\n]+\{value\}(?:;|")')
Check 'Players DTO Boundary' 'Desktop metadata DTOs expose notes and warnings but no server runtime path' ($playerMetadataDtos -match 'PlayerMetadataDto' -and $playerMetadataDtos -match 'PlayerWarningDto' -and $playerMetadataDtos -notmatch 'RuntimeRoot|MetadataPath|FilePath')
Check 'Players Polling' 'Players refresh reuses one aggregate status request without adding another timer' ($vm -match 'RefreshPlayersPageAsync' -and $vm -match 'GetStatusPollingAsync\(profile, 120' -and $vm -notmatch 'DispatcherTimer.*Players')
Check 'Button Presentation' 'Shared button style centers content and supplies metallic hover pressed disabled and focus states' ($appXaml -match 'Style Selector="Button"' -and $appXaml -match 'HorizontalContentAlignment" Value="Center"' -and $appXaml -match 'VerticalContentAlignment" Value="Center"' -and $appXaml -match 'MystTiqButtonMetal' -and $appXaml -match 'Button:pointerover' -and $appXaml -match 'Button:pressed' -and $appXaml -match 'Button:disabled' -and $appXaml -match 'Button:focus-visible')
Check 'Relaunch Guard' 'Desktop publish closes only artifact-hosted MystTiq desktop/sidecar processes and waits before relaunch' ($desktopBuild -match 'Stop-ExistingArtifactDesktop' -and $desktopBuild -match "ProcessName -notin @\('MystTiq\.Desktop','mysttiq-server'\)" -and $desktopBuild -match 'StartsWith\(\$guard' -and $desktopBuild -match 'WaitForExit\(5000\)' -and $desktopBuild.IndexOf('Stop-ExistingArtifactDesktop -ArtifactRoot') -lt $desktopBuild.LastIndexOf('Start-Process -FilePath $desktopExe'))

# In-memory stable-selection contract using refreshed instances with the same server-side ID.
$oldPlayer=[pscustomobject]@{PlayerId='steam_76561198000000001';Online=$true}
$newPlayers=@([pscustomobject]@{PlayerId='steam_76561198000000002';Online=$false},[pscustomobject]@{PlayerId='steam_76561198000000001';Online=$true})
$restoredPlayer=$newPlayers|Where-Object PlayerId -eq $oldPlayer.PlayerId|Select-Object -First 1
Check 'Players Behavioral Contract' 'Stable ID restores the selected player after refreshed object instances replace the list' ($null -ne $restoredPlayer -and $restoredPlayer.PlayerId -eq $oldPlayer.PlayerId)
Check 'Exit UX' 'Tray exposes safe force and GUI-only exit choices' ($appComposition -match 'SafeExit_OnClick' -and $appComposition -match 'ForceExit_OnClick' -and (Text 'src\MystTiq.Desktop\App.axaml') -match 'Safe Exit' -and (Text 'src\MystTiq.Desktop\App.axaml') -match 'Force Exit' -and (Text 'src\MystTiq.Desktop\App.axaml') -match 'Exit GUI Only')
Check 'Exit UX' 'Safe exit uses graceful lifecycle stop before owned sidecar shutdown' ($vm -match 'ShutdownForExitAsync' -and $vm -match '_api\.StopServerAsync' -and $appComposition -match 'StopOwnedSidecarAsync')
Check 'Exit UX' 'Force exit uses dedicated lifecycle force-stop API route' ($client -match '/api/v1/server/force-stop' -and $apiHostSource -match '/api/v1/server/force-stop' -and $apiHostSource -match 'StopAsync\(TimeSpan\.Zero')

Check 'Behavioral Contract' 'Aggregate wire sample accepts null lifecycle transition timestamp before first transition' ($null -eq $sample.status.lastTransitionAt)
Check 'Behavioral Contract' 'Aggregate wire sample preserves coherent server/service/player/metric/log state' (-not $sample.status.ready -and $sample.service.activeState -eq 'active' -and $sample.players.onlineCount -eq 3 -and $sample.metrics.threadCount -eq 42 -and $sample.logTail.lines[0] -eq 'ready')

if($RunBuild){
    & (Join-Path $root 'Build.ps1') -Action Validate -StrictValidation
    & (Join-Path $root 'Build.ps1') -Action Build -Configuration Release
    & (Join-Path $root 'Build.ps1') -Action WindowsHeadless -Configuration Release
    & (Join-Path $root 'Build.ps1') -Action LinuxHeadless -Configuration Release
    & (Join-Path $root 'Build.ps1') -Action DesktopWindows -Configuration Release
    & (Join-Path $root 'Build.ps1') -Action DesktopLinux -Configuration Release
    & (Join-Path $root 'scripts\Test-v0.4.10.0-RuntimeSmoke.ps1') -ProjectRoot $root
}
$failed=@($checks|Where-Object{-not $_.Passed})
Write-Host "`n================ MystTiq v0.4.10.0 Summary ================"
Write-Host "Passed: $($checks.Count-$failed.Count) / $($checks.Count)"
if($ExportJson){$dir=Join-Path $root 'artifacts\logic-tests';New-Item $dir -ItemType Directory -Force|Out-Null;$path=Join-Path $dir "MystTiq_v0.4.10.0_$(Get-Date -Format yyyyMMdd-HHmmss).json";$checks|ConvertTo-Json -Depth 4|Set-Content $path;Write-Host "JSON report: $path"}
if($failed.Count){$failed|Format-Table -AutoSize;throw "v0.4.10.0 logic gate failed: $($failed.Count) check(s)."}
Write-Host 'v0.4.10.0 logic gate passed.' -ForegroundColor Green
