using System.Text.Json;
using PalworldManager.Models;
namespace PalworldManager.Services;
public sealed class GuildTransactionService
{
    private readonly AppSettings settings; private static readonly JsonSerializerOptions JsonOptions=new(){WriteIndented=true};
    public GuildTransactionService(AppSettings settings)=>this.settings=settings;
    public string CreateBackup(string worldPath){if(!Directory.Exists(worldPath))throw new DirectoryNotFoundException(worldPath);var level=Path.Combine(worldPath,"Level.sav");if(!File.Exists(level))throw new FileNotFoundException("Level.sav was not found.",level);var root=Path.Combine(settings.BackupRoot??Path.Combine(settings.ServerRoot??"","Backups"),"GuildRepair");Directory.CreateDirectory(root);var destination=Path.Combine(root,$"GuildRepair_{DateTime.Now:yyyyMMdd_HHmmss_fff}");CopyDirectory(worldPath,destination);File.WriteAllText(Path.Combine(destination,"guild-repair-backup.json"),JsonSerializer.Serialize(new{source=worldPath,sourceHash=PalworldSaveCodec.HashFile(level),createdUtc=DateTime.UtcNow},JsonOptions));return destination;}
    public void ValidatePlan(GuildWorldSnapshot snapshot,GuildRepairPlan plan){if(snapshot.IsReadOnly&&snapshot.Mode==GuildSnapshotMode.None)throw new InvalidOperationException("No decoded Level.sav is loaded.");if(plan.Operations.Count==0)throw new InvalidOperationException("The repair plan contains no operations.");if(!string.IsNullOrWhiteSpace(plan.SourceHash)&&plan.SourceHash!=snapshot.SourceHash)throw new InvalidOperationException("The repair plan was created from a different Level.sav revision.");foreach(var op in plan.Operations){var g=snapshot.Guilds.SingleOrDefault(x=>x.GuildId.Equals(op.GuildId,StringComparison.OrdinalIgnoreCase))??throw new InvalidOperationException($"Guild {op.GuildId} no longer exists.");if(op.Type is GuildRepairOperationType.ClaimOrphanedGuild or GuildRepairOperationType.TransferLeadership or GuildRepairOperationType.AddPlayerToGuild)new GuildPlayerIdentityService().ResolveRequired(snapshot,op.PlayerUid);if(op.Type==GuildRepairOperationType.ClaimOrphanedGuild&&!g.IsOrphaned)throw new InvalidOperationException($"Guild {g.Name} is not orphaned.");}var dup=plan.Operations.GroupBy(x=>$"{x.Type}|{x.GuildId}|{x.PlayerUid}|{x.BaseId}",StringComparer.OrdinalIgnoreCase).FirstOrDefault(g=>g.Count()>1);if(dup!=null)throw new InvalidOperationException("The plan contains duplicate operations.");}
    public string StagePlan(GuildRepairPlan plan){var dir=Path.Combine(Path.GetTempPath(),"MystTiqPalworldServer","GuildRepair",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var path=Path.Combine(dir,"guild-repair-plan.json");File.WriteAllText(path,JsonSerializer.Serialize(plan,JsonOptions));return path;}
    public void Rollback(string backupPath,string worldPath){if(!Directory.Exists(backupPath))throw new DirectoryNotFoundException(backupPath);if(Directory.Exists(worldPath))Directory.Delete(worldPath,true);CopyDirectory(backupPath,worldPath,true);}
    internal static void CopyDirectory(string source,string destination,bool skipMarker=false){Directory.CreateDirectory(destination);foreach(var file in Directory.EnumerateFiles(source)){if(skipMarker&&Path.GetFileName(file)=="guild-repair-backup.json")continue;File.Copy(file,Path.Combine(destination,Path.GetFileName(file)),true);}foreach(var dir in Directory.EnumerateDirectories(source))CopyDirectory(dir,Path.Combine(destination,Path.GetFileName(dir)),skipMarker);}
}
